// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = 'https://ssl.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  ;
    var getBookmarksHTML, results, search;
    results = $('#results');
    search = $('#search');
    search.focus();
    search.on('keyup', function() {
      var newSearch;
      newSearch = $(this).val();
      return chrome.bookmarks.search(newSearch, function(res) {
        return results.html(getBookmarksHTML(res));
      });
    });
    return getBookmarksHTML = function(bookmarks) {
      var bookmark, buildHtml, output, _i, _len;
      output = '<ul class="results-list">';
      buildHtml = function(bookmark) {
        return "<li><a href=\"" + bookmark.url + "\" target=\"_blank\">" + bookmark.title + "</a></li>";
      };
      for (_i = 0, _len = bookmarks.length; _i < _len; _i++) {
        bookmark = bookmarks[_i];
        output += buildHtml(bookmark);
      }
      return output += '</ul>';
    };
  });

}).call(this);
